version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/tests/create_vpn_gateway"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/tests/create_vpn_gateway_with_connections"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
