version: 1

update_configs:

  - package_manager: "terraform"
    directory: "/"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_vpn_gateway"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/create_customer_gateway"
    update_schedule: "daily"

  - package_manager: "terraform"
    directory: "/tests/no_create"
    update_schedule: "daily"

  - package_manager: "go:modules"
    directory: "/tests"
    update_schedule: "daily"
